FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY apps/frontend ./apps/frontend
COPY libs ./libs
COPY tsconfig.base.json ./
RUN npx nx build frontend --configuration=production

FROM nginx:alpine AS runner
COPY --from=builder /app/dist/apps/frontend/browser /usr/share/nginx/html
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
